### ISSUE TITLE
Inconsistent Writing of Preference File Values

### ISSUE THREAD

**Issue by 0xmachos** [theevilbit/Shield#12] opened 2021-02-09 00:18 UTC
macOS Version: macOS `11.2` (`20D64`)
Kernel Version: Darwin `20.3.0`
Shield Version: `v0.9.5`
User Type: Admin
Terminal Full Disk Access: Yes
SIP: Enabled

While discovering #11 I noticed that the value of `isRunning` is not consistantly updated in the `PREFS_FILE ` (`com.csaba.fitzl.shield.preferences.plist`) when the UI Preferences Toggle is changed or the Menu Bar menu is used to start/ stop shield. 

It appears that the value of `isRunning` being updated in `com.csaba.fitzl.shield.preferences.plist` is linked to value of `isBlocking` being changed.

## Steps to Reproduce
1. Open Shield Preferences
2. Disable all injection protection settings
   * This is *not necessary for reproduction* it just makes it easier to read the `defaults` output later on 
3. Enable Shield and enable blocking mode
4. Execute `defaults read /Library/Application\ Support/Shield/com.csaba.fitzl.shield.preferences.plist`
   * The result should be:
```
isBlocking = 1;
isRunning = 1;
``` 
5. Disable Shield via the Shield Preferences UI or Menu Bar UI 
6. Execute `defaults read /Library/Application\ Support/Shield/com.csaba.fitzl.shield.preferences.plist`
   * The result should be:
```
isBlocking = 1;
isRunning = 1;
``` 
   * However the Shield Preferences UI and Menu Bar UI will indicate that Shield is stopped
7. Disable Blocking Mode
8. Execute `defaults read /Library/Application\ Support/Shield/com.csaba.fitzl.shield.preferences.plist`
   * The result should be:
```
isBlocking = 0;
isRunning = 0;
```
9. Enable Shield via the Shield Preferences UI or Menu Bar UI
   * Execute `defaults read /Library/Application\ Support/Shield/com.csaba.fitzl.shield.preferences.plist`
   * The result should be:
```
isBlocking = 0;
isRunning = 0;
```

These steps also work if you start with Blocking Mode disabled and enable it in step 7 rather than disabling it.

The value of `isRunning` is also not updated if you close the Shield Preferences window then execute the `defaults read` command.

**Comment by theevilbit** [comment] 2021-02-09 10:36
Indeed. I guess this was "by design", as I ignore the isRunning setting in beta completely. I will fix it in the next release, so even if it's ignored, it's still correctly saved.

**Comment by theevilbit** [comment] 2021-02-09 21:14
Fixed in https://github.com/theevilbit/Shield/commit/13c48e01fc9cf1ccb4f062c2dfbf000ef648239d

**Closed by theevilbit** 2021-02-09 21:14 UTC
